# 开发环境配置
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sky_blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # mysql 用户名
    password: 123456 # mysql 密码
  jpa:
    properties:
      hibernate:
        show_sql: true # 显示 sql 语句
        format_sql: true # 格式化 sql 语句
  # redis 配置
  redis:
    host: localhost # redis 主机地址
    port: 6379 # redis 端口号
    database: 8 # 操作的 redis 数据库(0-15)
    password: # redis 连接密码
    timeout: 20s # 超时时间
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1 # 连接池最大阻塞等待时间
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 2 # 连接池最小空闲连接

# 项目配置项
sky-blog:
  security: # 安全性配置
    jwt-key: fushengruomeng # 用于生成 JWT 令牌的 key
    token-expire-time: 86400000 # 令牌过期时间